#!/bin/bash
#
# Copyright (C) 2014-2015 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_PLUGIN_XPATH=/config/services/nginx
OMV_NGINX_SERVERS_XPATH=${OMV_PLUGIN_XPATH}/servers
OMV_NGINX_SERVER_XPATH=${OMV_NGINX_SERVERS_XPATH}/server

# Nginx paths.
NGINX_AVAILABLE_DIR=/etc/nginx/sites-available
NGINX_LOG_DIR=/var/log/nginx

OMV_NGINX_CUSTOM_CONF=/etc/nginx/conf.d/openmediavault-nginx.conf
OMV_NGINX_CONF=openmediavault-nginx

HOST_TYPE_PORT="port"
HOST_TYPE_NAME="name"

remove_server()
{
    nginx_dissite ${1} || true

    if [ -e "${NGINX_AVAILABLE_DIR}/${1}" ]; then
        rm "${NGINX_AVAILABLE_DIR}/${1}"
    fi
}

listen_options_undefined()
{
    # Match UUID with first result matching the port. This should only match
    # once and therefore set the options once.
    local port="${1}"
    local uuid="${2}"
    local webadmin_xpath="/config/webadmin[port='${port}' or sslport='${port}']"
    local xpath="${OMV_NGINX_SERVER_XPATH}[port='${port}' or ssl_port='${port}'][1][uuid='${uuid}']"

    # If using the ports OpenMediaVault is using, no options should be set.
    if [ $(omv_config_get_count "${webadmin_xpath}") -gt 0 ]; then
        return 1
    fi

    # If we get a match this is the entry that will get listen options.
    if [ $(omv_config_get_count "${xpath}") -gt 0 ]; then
        return 0
    fi

    return 1
}

generate_server_nginx_config()
{
    local xpath="${1}"
    local config="${2}"

    # Get document root if it's set.
    local root_ref=$(omv_config_get "${xpath}/sharedfolderref")
    local root=""
    local use_root=$(omv_config_get "${xpath}/use_root")
    local use_public_directory=$(omv_config_get "${xpath}/use_public_directory")
    local public_directory=$(omv_config_get "${xpath}/public_directory")

    if [ -n "${root_ref}" ]; then
        root=$(omv_get_sharedfolder_path "${root_ref}")

        if [ $use_root -eq 1 -a ${use_public_directory} -eq 1 ]; then
            root="${root}/${public_directory}"
        fi
    fi

    # Variables.
    local uuid=$(omv_config_get "${xpath}/uuid")
    local host_type=$(omv_config_get "${xpath}/host_type")
    local server_name=$(omv_config_get "${xpath}/server_name")
    local port=$(omv_config_get "${xpath}/port")
    local port_default_server=$(omv_config_get "${xpath}/port_default_server")

    # SSL.
    local ssl_enable=$(omv_config_get "${xpath}/ssl_enable")
    local ssl_port=$(omv_config_get "${xpath}/ssl_port")
    local ssl_port_default_server=$(omv_config_get "${xpath}/ssl_port_default_server")
    local sslcertificateref=$(omv_config_get "${xpath}/sslcertificateref")
    local ssl_force=$(omv_config_get "${xpath}/ssl_force")

    # PHP.
    local php_enable=$(omv_config_get "${xpath}/php_enable")
    local php_pool_ref=$(omv_config_get "${xpath}/php_pool_ref")
    local php_use_default_config=$(omv_config_get "${xpath}/php_use_default_config")

    # Options.
    local use_index=$(omv_config_get "${xpath}/use_index")
    local use_index_html=$(omv_config_get "${xpath}/use_index_html")
    local use_index_php=$(omv_config_get "${xpath}/use_index_php")
    local autoindex=$(omv_config_get "${xpath}/autoindex")
    local deny_htaccess=$(omv_config_get "${xpath}/deny_htaccess")
    local log_enable=$(omv_config_get "${xpath}/log_enable")
    local large_client_header_buffers=$(omv_config_get "${xpath}/large_client_header_buffers")

    # Start generating configuration file.
    echo "server {" >> ${config}

    # Non SSL configuration.
    # Always listen to port unless SSL is forced.
    if [ $ssl_force -ne 1 ]; then
        local listen_options="[::]:${port}"

        if [ $port_default_server -eq 1 ]; then
            listen_options+=" default_server"
        fi

        if listen_options_undefined ${port} ${uuid}; then
            listen_options+=" ipv6only=off"
        fi

        echo "    listen ${listen_options};" >> ${config}
    fi

    # SSL configuration.
    if [ $ssl_enable -eq 1 ]; then
        local ssl_listen_options="[::]:${ssl_port} ssl"

        if [ $ssl_port_default_server -eq 1 ]; then
            ssl_listen_options+=" default_server"
        fi

        if listen_options_undefined ${ssl_port} ${uuid}; then
            ssl_listen_options+=" ipv6only=off"
        fi

        echo "    listen ${ssl_listen_options};" >> ${config}
        echo "    ssl_certificate     ${OMV_SSL_CERTIFICATE_DIR}/certs/${OMV_SSL_CERTIFICATE_PREFIX}${sslcertificateref}.crt;" >> ${config}
        echo "    ssl_certificate_key ${OMV_SSL_CERTIFICATE_DIR}/private/${OMV_SSL_CERTIFICATE_PREFIX}${sslcertificateref}.key;" >> ${config}
    fi

    # Set the server_name option if the server is name-based.
    if [ $host_type = $HOST_TYPE_NAME ]; then
        echo "    server_name ${server_name};" >> ${config}
    fi

    if [ -n "${root}" ]; then
        # Add root_path variable.
        echo "    set \$root_path \"${root}\";" >> ${config}

        # Set the root option if it's enabled.
        if [ $use_root -eq 1 ]; then
            echo "    root \$root_path;" >> ${config}
        fi
    fi

    # Add valid index files.
    if [ $use_index -eq 1 ]; then
        local index_files=""

        if [ $use_index_html -eq 1 ]; then
            index_files+=" index.html"
        fi

        if [ $use_index_php -eq 1 ]; then
            index_files+=" index.php"
        fi

        echo "    index${index_files};" >> ${config}
    fi

    # Add $socket variable if PHP is enabled.
    if [ $php_enable -eq 1 ]; then
        echo "    set \$socket \"unix:/var/run/fpm-${php_pool_ref}.sock\";" >> ${config}
    fi

    # Add default PHP configuration if it's enabled.
    if [ $php_enable -eq 1 -a $php_use_default_config  -eq 1 ]; then
        echo "    location ~ \.php$ {" >> ${config}
        echo "        fastcgi_split_path_info ^(.+\.php)(/.+)$;" >> ${config}
        echo "        fastcgi_pass \$socket;" >> ${config}
        echo "        fastcgi_index index.php;" >> ${config}
        echo "        include fastcgi_params;" >> ${config}
        echo "    }" >> ${config}
    fi

    # Enable logs.
    if [ $log_enable -eq 1 ]; then
        echo "    access_log ${NGINX_LOG_DIR}/${uuid}-access.log;" >> ${config}
        echo "    error_log  ${NGINX_LOG_DIR}/${uuid}-error.log;" >> ${config}
    fi

    # Add other options.
    if [ $autoindex -eq 1 ]; then
        echo "    autoindex on;" >> ${config}
    fi

    if [ $deny_htaccess -eq 1 ]; then
        echo "    location ~ /\.ht {" >> ${config}
        echo "        deny all;" >> ${config}
        echo "    }" >> ${config}
    fi

    echo "    large_client_header_buffers 4 ${large_client_header_buffers}k;" >> ${config}

    # Add extra options.
    xmlstarlet sel -t -m "${xpath}" \
        -i "string-length(extra_options) > 0" \
            -o "    " -v extra_options -n \
        -b \
        ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${config}

    echo "}" >> ${config}
    echo "" >> ${config}
}

remove_nginx_logs()
{
    find ${NGINX_LOG_DIR} -type f -regextype sed -regex ".*/[a-f0-9\-]\{36\}.*" -exec rm {} \;
}

generate_nginx_config()
{
    local size=$(omv_config_get "${OMV_PLUGIN_XPATH}/server_names_hash_bucket_size")
    echo "server_names_hash_bucket_size ${size};" > ${OMV_NGINX_CUSTOM_CONF}
}

nginx_dissite ${OMV_NGINX_CONF} || true
remove_nginx_logs
generate_nginx_config

if [ "$(omv_config_get "${OMV_PLUGIN_XPATH}/enable")" -eq "1" ]; then

    # Remove old config remove_config.
    remove_server ${OMV_NGINX_CONF}

    # Iterate through enabled servers.
    server_count=$(omv_config_get_count "${OMV_NGINX_SERVER_XPATH}[enable = '1']")
    index=1

    while [ $index -lt $server_count -o $index -eq $server_count ]; do

        current_server_xpath="${OMV_NGINX_SERVER_XPATH}[enable = '1'][${index}]"
        generate_server_nginx_config "${current_server_xpath}" "${NGINX_AVAILABLE_DIR}/${OMV_NGINX_CONF}"

        index=$(( ${index} + 1 ))

    done

    nginx_ensite ${OMV_NGINX_CONF} || true
fi

exit 0
