#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_NGINX_CONF_NAME=openmediavault-nginx
OMV_NGINX_CUSTOM_CONF=/etc/nginx/conf.d/${OMV_NGINX_CONF_NAME}.conf
NGINX_AVAILABLE_DIR=/etc/nginx/sites-available
NGINX_ENABLED_DIR=/etc/nginx/sites-enabled

remove_fpm_configs()
{
    find /etc/php5/fpm/pool.d -type f -regextype sed -regex ".*/[a-f0-9\-]\{36\}.*" -exec rm {} \;
}

remove_nginx_configs()
{
    if [ -e "${OMV_NGINX_CUSTOM_CONF}" ]; then
        rm "${OMV_NGINX_CUSTOM_CONF}"
    fi

    # Remove file in sites-enabled
    if [ -e "${NGINX_ENABLED_DIR}/${1}" ]; then
        rm "${NGINX_ENABLED_DIR}/${1}"
    fi

    # Remove file in sites-available
    if [ -e "${NGINX_AVAILABLE_DIR}/${1}" ]; then
        rm "${NGINX_AVAILABLE_DIR}/${1}"
    fi
}

remove_nginx_logs()
{
    find /var/log/nginx -type f -regextype sed -regex ".*/[a-f0-9\-]\{36\}.*" -exec rm {} \;
}

case "$1" in
    purge)
        omv_config_delete "/config/services/nginx"
        omv_config_delete "/config/services/phpfpm"
    ;;

    remove)
        remove_nginx_configs ${OMV_NGINX_CONF_NAME}
        remove_nginx_logs
        remove_fpm_configs

        if [ -x "/etc/init.d/nginx" ]; then
            invoke-rc.d nginx reload
        fi

        if [ -x "/etc/init.d/php5-fpm" ]; then
            invoke-rc.d php5-fpm reload
        fi
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
