#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="nginx"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "server_names_hash_bucket_size" "32"
            omv_config_add_element "${SERVICE_XPATH}" "servers"
        fi

        # Disable the default Nginx site
        NGINX_DEFAULT_ENABLED_CONF=/etc/nginx/sites-enabled/default

        if [ -e "${NGINX_DEFAULT_ENABLED_CONF}" ]; then
            /bin/rm "${NGINX_DEFAULT_ENABLED_CONF}"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
