#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        SERVICE_XPATH_NAME="nginx"
        SERVICE_XPATH="/config/services/$SERVICE_XPATH_NAME"

        if ! omv_config_exists "$SERVICE_XPATH"; then
            omv_config_add_element "/config/services" "$SERVICE_XPATH_NAME"
            omv_config_add_element "$SERVICE_XPATH" "enable" "0"
            omv_config_add_element "$SERVICE_XPATH" "server_names_hash_bucket_size" "32"
            omv_config_add_element "$SERVICE_XPATH" "servers"
        fi

        SERVICE_PHPFPM_XPATH_NAME="phpfpm"
        SERVICE_PHPFPM_XPATH="/config/services/$SERVICE_PHPFPM_XPATH_NAME"

        if ! omv_config_exists "$SERVICE_PHPFPM_XPATH"; then
            omv_config_add_element "/config/services" "$SERVICE_PHPFPM_XPATH_NAME"
            omv_config_add_element "$SERVICE_PHPFPM_XPATH" "pools"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
